name: motion_week2_sg
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.3
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/images/splashLogo.png

flutter_native_splash:
  color: "#00623b"
  image: "assets/images/splashLogo.png"
  android: true
  ios: true
