// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Fczcxq8bjMMdVpm2kf3eMYi4uPSfhmo',
    appId: '1:428897764556:web:47f7bd59544a9c85a66e69',
    messagingSenderId: '428897764556',
    projectId: 'motion-to-do',
    authDomain: 'motion-to-do.firebaseapp.com',
    storageBucket: 'motion-to-do.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtvybApH8gG1z2vbWVYddEXQ945avosOA',
    appId: '1:428897764556:android:fe34836867578bc7a66e69',
    messagingSenderId: '428897764556',
    projectId: 'motion-to-do',
    storageBucket: 'motion-to-do.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmh-HpnicE9-WjOhaPja9f68PX3PQxO5A',
    appId: '1:428897764556:ios:7560353fbe974026a66e69',
    messagingSenderId: '428897764556',
    projectId: 'motion-to-do',
    storageBucket: 'motion-to-do.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmh-HpnicE9-WjOhaPja9f68PX3PQxO5A',
    appId: '1:428897764556:ios:7560353fbe974026a66e69',
    messagingSenderId: '428897764556',
    projectId: 'motion-to-do',
    storageBucket: 'motion-to-do.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Fczcxq8bjMMdVpm2kf3eMYi4uPSfhmo',
    appId: '1:428897764556:web:30c41332558ee7c0a66e69',
    messagingSenderId: '428897764556',
    projectId: 'motion-to-do',
    authDomain: 'motion-to-do.firebaseapp.com',
    storageBucket: 'motion-to-do.firebasestorage.app',
  );

}